### ISSUE TITLE
Not obvious how to use sqrt

### ISSUE THREAD

**Issue by rebcabin** [alanforr/complex#1]
I found that I must call sqrt in an unintuitive way to get a usable result.  In a REPL, I find that the result of calling sqrt is a function and not a complex number

```
; CIDER 0.10.0snapshot (package: 20150818.441) (Java 1.8.0_51, Clojure 1.6.0, nREPL 0.2.6) 
complex.core> (sqrt -1)
#<core$sqrt$fn__78 complex.core$sqrt$fn__78@15c24abc>
complex.core> (stringify (sqrt -1))
"complex.core$sqrt$fn__78@48ebc65e"
complex.core> (real-part (sqrt -1))
ClassCastException complex.core$sqrt$fn__78 cannot be cast to org.apache.commons.math3.complex.Complex  complex.core/real-part (core.clj:100)
```

I can work around by calling that function

```
complex.core> ((sqrt 2345) -1)
#<Complex (0.0, 1.0)>
complex.core> ((sqrt 3456) (complex -1 0))
#<Complex (0.0, 1.0)>
```

but this is hardly satisfactory because of the necessary but meaningless argument to sqrt.  If I leave out the argument, things don't work

```
complex.core> ((sqrt) -1)
ArityException Wrong number of args (0) passed to: core/sqrt  clojure.lang.AFn.throwArity (AFn.java:429)
```

Perhaps I completely misunderstand the library, or perhaps I don't understand how the underlying java library (apache.commons.math3.complex) is supposed to work, but this is where I got by intuition.  

I will try to dig into the apache library from the java side to try to understand this better.  Perhaps you can see a solution more quickly or insightfully?

**Comment by alanforr** [comment]
On 19 Aug 2015, at 14:02, rebcabin notifications@github.com wrote:

> I found that I must call sqrt in an unintuitive way to get a usable result. In a REPL, I find that the result of calling sqrt is a function and not a complex number
> 
> ; CIDER 0.10.0snapshot (package: 20150818.441) (Java 1.8.0_51, Clojure 1.6.0, nREPL 0.2.6) complex.core> (sqrt -1)
> #<core$sqrt$fn__78 complex.core$sqrt$fn__78@15c24abc>
> complex.core> (stringify (sqrt -1))
> "complex.core$sqrt$fn__78@48ebc65e"
> complex.core> (real-part (sqrt -1))
> ClassCastException complex.core$sqrt$fn__78 cannot be cast to org.apache.commons.math3.complex.Complex  complex.core/real-part (core.clj:100)
> 
> I can work around by calling that function
> 
> complex.core> ((sqrt 2345) -1)
> #<Complex (0.0, 1.0)>
> complex.core> ((sqrt 3456) (complex -1 0))
> #<Complex (0.0, 1.0)>
> 
> but this is hardly satisfactory because of the necessary but meaningless argument to sqrt. If I leave out the argument, things don't work
> 
> complex.core> ((sqrt) -1)
> ArityException Wrong number of args (0) passed to: core/sqrt  clojure.lang.AFn.throwArity (AFn.java:429)
> 
> Perhaps I completely misunderstand the library, or perhaps I don't understand how the underlying java library (apache.commons.math3.complex) is supposed to work, but this is where I got by intuition.
> 
> I will try to dig into the apache library from the java side to try to understand this better. Perhaps you can see a solution more quickly or insightfully?

There is no need to dig into the library. I have found the cause of the bug and will patch it soon.

Alan

**Comment by alanforr** [comment]
Thanks for notifying me of the problem. I have fixed it, and pushed the fix to Clojars.

**Comment by rebcabin** [comment]
Great!  Tested in my world.  

May I impose on you for a word of explanation?  I looked at the source and couldn't see the problem (else I would have fixed it and sent you a pull request :).  Looks like you just inserted an extra layer of function, but it looked there were already too many layers ...  well, I'm just confused about it.

**Comment by alanforr** [comment]
I didn't insert an extra layer of function. Originally, on each branch of the if statement, the function was returning a function without applying it to the value. I changed the code that it does apply the function to the value. 

I considered simplifying the function by just applying .sqrt to the value directly on the complex branch and to (complex value) on the real branch, but that made the function benchmark slower on the complex branch, so I'm not going to make that change. (This is probably a type hinting issue.)

**Comment by rebcabin** [comment]
Oh, I see it now.  Thanks.

**Comment by rebcabin** [comment]
At the risk of bikeshedding, I suppose a tiny DRY improvement might be

```
(defn sin
  "Computes the sine of the argument, which may or may not be complex, as a complex number."
  [a]
  ((if (number? a)
    (fn [x] (.sin (complex x)))
    (fn [^org.apache.commons.math3.complex.Complex x] (.sin x))) a))
```

which removes one reference to `a`

**Comment by alanforr** [comment]
If I were going to do that I'd put the whole function in a let and then apply it. I have simplified the first branch in the if statement as that has no performance cost.
